config/routes.rb
Bucketlist::Application.routes.draw do

  root :to => 'todo_items#index'  
  resources :comments 
  resources :todo_items, :only => [:show, :index, :create] do
    member do
        post 'like'
    end
  end
  # you can nest the todoitems
  resources :destinations, :only => [:create, :index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :todo_item_id
  
  belongs_to :todo_item

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :name 

  has_many :todo_items
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :todo_item_id, :user_id

  belongs_to :user
  belongs_to :todo_item
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :completed, :name, :location, :latitude, :longitude, :destination_id 
  # validates :location, :presence => true

  geocoded_by :geolocate 
  # after_validation :geocode

  has_many :comments
  belongs_to :destination

   def geolocate
     # glues on destination to every location
     "#{self.location} #{destination.name}"
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :my_todo_items, :class_name => 'TodoItem'

  has_many :likes
  has_many :liked_items, :through => :likes, :class_name => 'TodoItem'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create
        @comment = Comment.new(params[:comment])
        @comment.save!
        render @comment 
    end


end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

    def index
        @destination = Destination.all
    end


    def create
        @destination = Destination.new(params[:destination])
        @destination.save!
        render @destination
    end


end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

    def index
        @items = TodoItem.all
    end

    def create
        @item = TodoItem.new(params[:todo_item])
        @item.save!
        render @item
        # render :template => 'todo_items/create', :content_type => 'text/javascript????'
        #  local => ????????
    end

    def like

        #submits data but does not render anything 
        render :nothing => true
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/comments/_comment.html.erb
<!-- displays the comments-->
<div class="comment">
    <%= comment.body %> 
</div>

app/views/comments/_form.html.erb
<!-- partial with the comment text field and submit button -->
<div class="new-comments">
<!-- when you create a comment it takes the ID of item and and passes the value to the column todo_item_id that way comments know which item it belongs to  -->
    <%= form_for Comment.new(:todo_item_id => item.id), :remote => :true do |f| %>
        
        <%= f.hidden_field :todo_item_id %>

            <div class="field">
                <%= f.text_area :body %>
            </div>

            <div class="field">
                <%= f.submit %>
            </div>

    <% end %>
</div>

app/views/comments/index.html.erb
<h1>Here we are now</h1>

app/views/destinations/_destination.html.erb
<div class="destinations"/>

<h3><%#= @destination %></h3>


<div class="destinations">
    <%# @destination.each do |d| %>
    
        <%#= render d %>
          
    <%# end %>
</div>

app/views/destinations/_form.html.erb
<div class = "destination_form">

    <h3>New Destination</h3>
    <%= form_for(Destination.new, :remote => true) do |f| %>
    <div class = "field">
            <%= f.text_field :name %>
    </div>
    <div class = "field">
            <%= f.submit  %>
    </div>
    <% end %>


</div>

app/views/destinations/show.html.erb
<%= render @destination %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Bucketlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

 

    <script type="text/javascript">
      
    </script>


  </head>
  <body>
 
    <%= yield %>
  </body>
</html>

app/views/todo_items/_create_item.html.erb
<div class="item-form">
    <%= form_for TodoItem.new do |f| %>

                <%= f.text_field :destination_id %>


            <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%= f.label :location %>
                <%= f.text_field :location %>
            </div>

            <div class="field">
                <%= f.submit %>
            </div>
    <% end %>
</div>

app/views/todo_items/_todo_item.html.erb
<!-- lists each to do item -->
<div class="todo-item <%= todo_item.completed? ? 'completed' : ''%>">
    <%= todo_item.name %>
</div>

<!-- renders comments using partial  -->
:
<!-- this is the div that is appended to by ajax -->
<div class ="comments">
    <% todo_item.comments.each do |comment| %>
        <%= render comment %>
    <% end %>
</div>

<!-- renders the comments form -->
<%= render :partial => 'comments/form', :locals => {:item => todo_item} %>


<!-- like image -->
<%= link_to image_tag('like.png', :width => 16, :height => 16), like_todo_item_path(todo_item.id), :remote => true, :method => :post %>

<!-- displays the time at which the item was -->
<div class="info">
    Posted <%= distance_of_time_in_words(Time.now, todo_item.created_at) %> ago
</div>

app/views/todo_items/index.html.erb
<div class="banner">

    <h1>The Bucket List</h1>
    <p>A todo-list.... before you die :-(</p>
</div>
<div id="search">
    <input type="text" class="search" placeholder="Enter a search term">
</div>


<!-- renders destination form -->
<%= render :partial => 'destinations/form' %>
<br>
New Destination
<%= render :partial => 'todo_items/create_item' %>

<div id="map-canvas">
</div>


<body>
    <!-- locals passes variables that are within scope --> 
    <%#= render :partial => 'todo_items/create_item', :locals => {:destination => d.id} %>
    
    <%= render :partial => 'destinations/destination' %>

    <% @items.each do |i| %>
         <%= render i %>
     <% end %>
</body>

app/views/todo_items/show.html.erb
<h1>This is the item</h1>

<%= render @item %> 